# Generated by Django 3.1.4 on 2020-12-13 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20201213_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='precio',
            field=models.TextField(null=True),
        ),
    ]
